# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4eb3f4381d0691e4e8d5e72f5d163b0b5c758345f3038081e1de46f95255d66f056e15b0646e73788835340137c72f189c094cc08ab8fbc1388c505d5703ab0

test:
  secret_key_base: 77f6d8465731fa12fe5a9e06d523c80f1848df2900f29e52f341acfbfad5829a289bfc0756a9b0563d868a4b3430d77449156b54769239fb50f52a00d06af84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
